# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST localhost:8822/api/auth/token
Content-Type: application/json

{
  "username": "ld",
  "password": "ld123"
}
###

GET localhost:8822/api/user/me
Authorization: token MTU1MjgwMTg0NTUwNDpiN2Y5YWNjOWFjZjRkNDYzNjU0ZjUyNTA1MDQyZTU4NGIzYjg4ZWU0ZmZkOGMwZjQ2NjhkYmEyMjg4NWZjZmYwOmxkOjNiNjgwYzQxMDM1OTY5ZWE4NGExZmY0NDA3ZTQ5OGRkMDNiMDYzMzcyNTRlNGNlYmIxZGJjMmEzNmVjZDA1NWU3ODhkMzlhNWFkZGUzOWRiYzc1NjU3MDRmMTFkOGY1YWFmMGI1OGZhMzllZjZjYmQzZDNhOWU2MTUyNDBlZGFi

###




