-- MySQL Script generated by MySQL Workbench
-- Sat Mar 23 15:06:50 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tour
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `tour_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tour_user`;

CREATE TABLE IF NOT EXISTS `tour_user`
(
  `id`         BIGINT       NOT NULL AUTO_INCREMENT,
  `username`   VARCHAR(32)  NOT NULL COMMENT '用户名，唯一',
  `nickname`   VARCHAR(128) NOT NULL COMMENT '昵称',
  `avatar`     VARCHAR(64)  NULL COMMENT '头像',
  `self_intro` VARCHAR(512) NULL COMMENT '自我介绍',
  `gender`     TINYINT      NULL DEFAULT 0 COMMENT '性别',
  `birth`      DATE         NULL COMMENT '出生日期',
  `region_id`  SMALLINT(5)  NULL DEFAULT NULL COMMENT '所在地区',
  `email`      VARCHAR(128) NULL DEFAULT '' COMMENT '邮箱',
  `user_type`  TINYINT      NULL DEFAULT 0 COMMENT '用户类型',
  `password`   VARCHAR(64)  NULL,
  `enabled`    TINYINT(1)   NULL DEFAULT 0 COMMENT '是否可用',
  `created_at` BIGINT       NULL,
  `updated_at` BIGINT       NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC)
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_spot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tour_spot`;

CREATE TABLE IF NOT EXISTS `tour_spot`
(
  `id`            BIGINT        NOT NULL AUTO_INCREMENT,
  `zh_name`       VARCHAR(256)  NULL COMMENT '景点名称_zh',
  `en_name`       VARCHAR(256)  NULL COMMENT '景点名称_en',
  `intro`         TEXT          NULL COMMENT '景点介绍',
  `cover_url`     VARCHAR(256)  NULL COMMENT '景点封面 url',
  `location`      VARCHAR(512)  NULL COMMENT '景点位置',
  `longitude`     DOUBLE(10, 6) NULL COMMENT '经度',
  `latitude`      DOUBLE(10, 6) NULL COMMENT '纬度',
  `phone`         VARCHAR(256)  NULL COMMENT '景点电话',
  `website`       VARCHAR(256)  NULL COMMENT '景点网站',
  `time_usage`    VARCHAR(64)   NULL COMMENT '游玩用时参考',
  `transport`     VARCHAR(512)  NULL COMMENT '交通',
  `open_time`     VARCHAR(512)  NULL COMMENT '开放时间',
  `went_count`    INT           NULL DEFAULT 0 COMMENT '去过的人数',
  `collect_count` INT           NULL DEFAULT 0 COMMENT '收藏数量',
  `photo_count`   INT           NULL DEFAULT 0 COMMENT '照片数量',
  `created_at`    BIGINT        NULL,
  `updated_at`    BIGINT        NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_spot_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tour_spot_comment`;

CREATE TABLE IF NOT EXISTS `tour_spot_comment`
(
  `id`         BIGINT        NOT NULL AUTO_INCREMENT,
  `spot_id`    BIGINT        NOT NULL COMMENT '景点 id',
  `author_id`  BIGINT        NOT NULL COMMENT '作者 id',
  `content`    VARCHAR(4000) NULL COMMENT '评论内容',
  `like_count` INT           NULL DEFAULT 0 COMMENT '点赞数量',
  `created_at` BIGINT        NULL,
  `updated_at` BIGINT        NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tour_spot_spot_id_idx` (`spot_id` ASC),
  INDEX `fk_tour_spot_author_id_idx` (`author_id` ASC),
  CONSTRAINT `fk_tour_spot_spot_id`
    FOREIGN KEY (`spot_id`)
      REFERENCES `tour_spot` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  CONSTRAINT `fk_tour_spot_author_id`
    FOREIGN KEY (`author_id`)
      REFERENCES `tour_user` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_travel_notes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tour_travel_notes`;

CREATE TABLE IF NOT EXISTS `tour_travel_notes`
(
  `id`            BIGINT       NOT NULL AUTO_INCREMENT,
  `title`         VARCHAR(512) NOT NULL COMMENT '标题',
  `content`       TEXT         NULL COMMENT '内容(富文本)',
  `author_id`     BIGINT       NULL COMMENT '作者 id',
  `like_count`    INT          NULL DEFAULT 0 COMMENT '点赞数量',
  `collect_count` INT          NULL DEFAULT 0 COMMENT '收藏数量',
  `share_count`   INT          NULL COMMENT '分享数量',
  `start_time`    BIGINT       NULL COMMENT '出发时间',
  `days_used`     INT          NULL COMMENT '用时(天)',
  `cost_average`  INT          NULL COMMENT '人均花费',
  `created_at`    BIGINT       NULL,
  `updated_at`    BIGINT       NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_travel_notes_author_id_idx` (`author_id` ASC),
  CONSTRAINT `fk_travel_notes_author_id`
    FOREIGN KEY (`author_id`)
      REFERENCES `tour_user` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_spot_photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tour_spot_photo`;

CREATE TABLE IF NOT EXISTS `tour_spot_photo`
(
  `id`              BIGINT       NOT NULL AUTO_INCREMENT,
  `file_url`        VARCHAR(256) NOT NULL COMMENT '文件 url',
  `description`     VARCHAR(256) NULL COMMENT '描述',
  `width`           INT          NULL DEFAULT -1 COMMENT '图片宽度',
  `height`          INT          NULL DEFAULT -1 COMMENT '图片高度',
  `spot_id`         BIGINT       NULL COMMENT '景点 id',
  `comment_id`      BIGINT       NULL COMMENT '评论 id',
  `travel_notes_id` BIGINT       NULL COMMENT '游记 id',
  `author_id`       BIGINT       NULL COMMENT '上传者',
  `photo_from`      TINYINT      NULL COMMENT '照片所在实体(评论, 游记)',
  `created_at`      BIGINT       NULL,
  `updated_at`      BIGINT       NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tour_spot_comment_photo_spot_id_idx` (`spot_id` ASC),
  INDEX `fk_tour_spot_comment_photo_comment_id_idx` (`comment_id` ASC),
  INDEX `fk_tour_spot_photo_author_id_idx` (`author_id` ASC),
  INDEX `fk_tour_spot_photo_travel_notes_id_idx` (`travel_notes_id` ASC),
  CONSTRAINT `fk_tour_spot_photo_spot_id`
    FOREIGN KEY (`spot_id`)
      REFERENCES `tour_spot` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  CONSTRAINT `fk_tour_spot_photo_comment_id`
    FOREIGN KEY (`comment_id`)
      REFERENCES `tour_spot_comment` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  CONSTRAINT `fk_tour_spot_photo_author_id`
    FOREIGN KEY (`author_id`)
      REFERENCES `tour_user` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  CONSTRAINT `fk_tour_spot_photo_travel_notes_id`
    FOREIGN KEY (`travel_notes_id`)
      REFERENCES `tour_travel_notes` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_travel_notes_spot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tour_travel_notes_spot`;

CREATE TABLE IF NOT EXISTS `tour_travel_notes_spot`
(
  `spot_id`         BIGINT NOT NULL,
  `travel_notes_id` BIGINT NOT NULL,
  PRIMARY KEY (`spot_id`, `travel_notes_id`),
  INDEX `fk_travel_notes_spot_notes_id_idx` (`travel_notes_id` ASC),
  CONSTRAINT `fk_travel_notes_spot_spot_id`
    FOREIGN KEY (`spot_id`)
      REFERENCES `tour_spot` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  CONSTRAINT `fk_travel_notes_spot_notes_id`
    FOREIGN KEY (`travel_notes_id`)
      REFERENCES `tour_travel_notes` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_like_rel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tour_like_rel`;

CREATE TABLE IF NOT EXISTS `tour_like_rel`
(
  `user_id`    BIGINT  NOT NULL COMMENT '点赞用户 id',
  `obj_id`     BIGINT  NOT NULL COMMENT '被点赞实体 id',
  `obj_type`   TINYINT NOT NULL COMMENT '被点赞实体 类型',
  `created_at` BIGINT  NULL,
  `updated_at` BIGINT  NULL,
  INDEX `idx_tour_like_rel_user_id` (`user_id` ASC),
  CONSTRAINT `fk_tour_like_rel_user_id`
    FOREIGN KEY (`user_id`)
      REFERENCES `tour_user` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_collect_rel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tour_collect_rel`;

CREATE TABLE IF NOT EXISTS `tour_collect_rel`
(
  `user_id`    BIGINT  NOT NULL COMMENT '收藏用户 id',
  `obj_id`     BIGINT  NOT NULL COMMENT '被收藏实体 id',
  `obj_type`   TINYINT NOT NULL COMMENT '被收藏实体 类型',
  `created_at` BIGINT  NULL,
  `updated_at` BIGINT  NULL,
  INDEX `idx_tour_collect_rel_user_id` (`user_id` ASC),
  CONSTRAINT `fk_tour_collect_rel_user_id`
    FOREIGN KEY (`user_id`)
      REFERENCES `tour_user` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_spot_ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tour_spot_ticket`;

CREATE TABLE IF NOT EXISTS `tour_spot_ticket`
(
  `id`         BIGINT       NOT NULL AUTO_INCREMENT,
  `spot_id`    BIGINT       NULL COMMENT '景点 id',
  `title`      VARCHAR(512) NULL COMMENT '门票信息',
  `price`      INT          NULL DEFAULT 0 COMMENT '价格',
  `created_at` BIGINT       NULL,
  `updated_at` BIGINT       NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tour_spot_ticket_spot_id_idx` (`spot_id` ASC),
  CONSTRAINT `fk_tour_spot_ticket_spot_id`
    FOREIGN KEY (`spot_id`)
      REFERENCES `tour_spot` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_spot_food`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tour_spot_food`;

CREATE TABLE IF NOT EXISTS `tour_spot_food`
(
  `id`               BIGINT        NOT NULL AUTO_INCREMENT,
  `title`            VARCHAR(256)  NULL COMMENT '标题',
  `description`      TEXT          NULL COMMENT '描述(富文本)',
  `price_average`    INT           NULL COMMENT '人均价格',
  `longitude`        DOUBLE(10, 6) NULL COMMENT '经度',
  `latitude`         DOUBLE(10, 6) NULL COMMENT '纬度',
  `location`         VARCHAR(512)  NULL COMMENT '酒店位置',
  `phone`            VARCHAR(256)  NULL COMMENT '电话',
  `like_count`       INT           NULL COMMENT '点赞数量',
  `collection_count` INT           NULL COMMENT '收藏数量',
  `created_at`       BIGINT        NULL,
  `updated_at`       BIGINT        NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_spot_food_rel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tour_spot_food_rel`;

CREATE TABLE IF NOT EXISTS `tour_spot_food_rel`
(
  `spot_id` BIGINT NOT NULL,
  `food_id` BIGINT NOT NULL,
  PRIMARY KEY (`spot_id`, `food_id`),
  INDEX `fk_tour_spot_food_food_id_idx` (`food_id` ASC),
  CONSTRAINT `fk_tour_spot_food_rel_spot_id`
    FOREIGN KEY (`spot_id`)
      REFERENCES `tour_spot` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  CONSTRAINT `fk_tour_spot_food_food_id`
    FOREIGN KEY (`food_id`)
      REFERENCES `tour_spot_food` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_spot_hotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tour_spot_hotel`;

CREATE TABLE IF NOT EXISTS `tour_spot_hotel`
(
  `id`               BIGINT        NOT NULL AUTO_INCREMENT,
  `title`            VARCHAR(256)  NULL COMMENT '标题',
  `description`      TEXT          NULL COMMENT '描述(富文本)',
  `price_average`    INT           NULL COMMENT '人均价格',
  `longitude`        DOUBLE(10, 6) NULL COMMENT '经度',
  `latitude`         DOUBLE(10, 6) NULL COMMENT '纬度',
  `location`         VARCHAR(512)  NULL COMMENT '吃的位置',
  `phone`            VARCHAR(256)  NULL COMMENT '电话',
  `like_count`       INT           NULL COMMENT '点赞数量',
  `collection_count` INT           NULL COMMENT '收藏数量',
  `created_at`       BIGINT        NULL,
  `updated_at`       BIGINT        NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour_spot_hotel_rel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tour_spot_hotel_rel`;

CREATE TABLE IF NOT EXISTS `tour_spot_hotel_rel`
(
  `spot_id`  BIGINT NOT NULL,
  `hotel_id` BIGINT NOT NULL,
  PRIMARY KEY (`spot_id`, `hotel_id`),
  INDEX `fk_tour_spot_hotel_rel_hotel_id_idx` (`hotel_id` ASC),
  CONSTRAINT `fk_tour_spot_hotel_rel_spot_id`
    FOREIGN KEY (`spot_id`)
      REFERENCES `tour_spot` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  CONSTRAINT `fk_tour_spot_hotel_rel_hotel_id`
    FOREIGN KEY (`hotel_id`)
      REFERENCES `tour_spot_hotel` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
