-- MySQL Script generated by MySQL Workbench
-- Tue Apr  9 18:11:34 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tour_diagram
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `tour_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tour_user`
(
    `id`         BIGINT(20)                                                        NOT NULL AUTO_INCREMENT,
    `username`   VARCHAR(32) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci'  NOT NULL COMMENT '用户名，唯一',
    `nickname`   VARCHAR(128) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL COMMENT '昵称',
    `avatar`     VARCHAR(64)                                                       NULL COMMENT '头像',
    `self_intro` VARCHAR(512) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '自我介绍',
    `gender`     TINYINT(4)                                                        NULL DEFAULT '0' COMMENT '性别',
    `birth`      DATE                                                              NULL DEFAULT NULL COMMENT '出生日期',
    `region_id`  SMALLINT(5)                                                       NULL DEFAULT NULL COMMENT '所在地区',
    `email`      VARCHAR(128) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT '' COMMENT '邮箱',
    `user_type`  TINYINT(4)                                                        NULL DEFAULT '0' COMMENT '用户类型',
    `password`   VARCHAR(64) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci'  NULL DEFAULT NULL,
    `enabled`    TINYINT(1)                                                        NULL DEFAULT '0' COMMENT '是否可用',
    `created_at` BIGINT(20)                                                        NULL DEFAULT NULL,
    `updated_at` BIGINT(20)                                                        NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `username_UNIQUE` (`username` ASC)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tour_like_collect_rel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tour_like_collect_rel`
(
    `user_id`    BIGINT(20) NOT NULL COMMENT '收藏用户 id',
    `id`         BIGINT     NOT NULL,
    `obj_id`     BIGINT(20) NOT NULL COMMENT '被收藏实体 id',
    `obj_type`   TINYINT    NOT NULL COMMENT '被收藏实体 类型',
    `rel_type`   TINYINT    NOT NULL,
    `created_at` BIGINT(20) NULL DEFAULT NULL,
    `updated_at` BIGINT(20) NULL DEFAULT NULL,
    INDEX `idx_tour_collect_rel_user_id` (`user_id` ASC),
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tour_spot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tour_spot`
(
    `id`            BIGINT(20)                                                        NOT NULL AUTO_INCREMENT,
    `name`          VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '景点名称_zh',
    `intro`         TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci'         NULL DEFAULT NULL COMMENT '景点介绍',
    `cover_url`     VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '景点封面 url',
    `location`      VARCHAR(512) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '景点位置',
    `location_id`   SMALLINT(5)                                                       NULL COMMENT '所在地 district id',
    `longitude`     DOUBLE(10, 6)                                                     NULL DEFAULT NULL COMMENT '经度',
    `latitude`      DOUBLE(10, 6)                                                     NULL DEFAULT NULL COMMENT '纬度',
    `phone`         VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '景点电话',
    `website`       VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '景点网站',
    `time_usage`    VARCHAR(64) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci'  NULL DEFAULT NULL COMMENT '游玩用时参考',
    `transport`     VARCHAR(512) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '交通',
    `open_time`     VARCHAR(512) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '开放时间',
    `went_count`    INT(11)                                                           NULL DEFAULT '0' COMMENT '去过的人数',
    `collect_count` INT(11)                                                           NULL DEFAULT '0' COMMENT '收藏数量',
    `photo_count`   INT(11)                                                           NULL DEFAULT '0' COMMENT '照片数量',
    `created_at`    BIGINT(20)                                                        NULL DEFAULT NULL,
    `updated_at`    BIGINT(20)                                                        NULL DEFAULT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tour_spot_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tour_spot_comment`
(
    `id`         BIGINT(20)                                                         NOT NULL AUTO_INCREMENT,
    `spot_id`    BIGINT(20)                                                         NOT NULL COMMENT '景点 id',
    `author_id`  BIGINT(20)                                                         NOT NULL COMMENT '作者 id',
    `content`    VARCHAR(4000) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '评论内容',
    `like_count` INT(11)                                                            NULL DEFAULT '0' COMMENT '点赞数量',
    `created_at` BIGINT(20)                                                         NULL DEFAULT NULL,
    `updated_at` BIGINT(20)                                                         NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_tour_spot_spot_id_idx` (`spot_id` ASC),
    INDEX `fk_tour_spot_author_id_idx` (`author_id` ASC)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tour_spot_food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tour_spot_food`
(
    `id`            BIGINT(20)                                                        NOT NULL AUTO_INCREMENT,
    `name`          VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '标题',
    `description`   TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci'         NULL DEFAULT NULL COMMENT '描述(富文本)',
    `price_average` INT(11)                                                           NULL DEFAULT NULL COMMENT '人均价格',
    `longitude`     DOUBLE(10, 6)                                                     NULL DEFAULT NULL COMMENT '经度',
    `latitude`      DOUBLE(10, 6)                                                     NULL DEFAULT NULL COMMENT '纬度',
    `location_id`   SMALLINT(5)                                                       NULL,
    `location`      VARCHAR(512) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '酒店位置',
    `phone`         VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '电话',
    `like_count`    INT(11)                                                           NULL DEFAULT NULL COMMENT '点赞数量',
    `collect_count` INT(11)                                                           NULL DEFAULT NULL COMMENT '收藏数量',
    `created_at`    BIGINT(20)                                                        NULL DEFAULT NULL,
    `updated_at`    BIGINT(20)                                                        NULL DEFAULT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tour_spot_food_rel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tour_spot_food_rel`
(
    `spot_id` BIGINT(20) NOT NULL,
    `food_id` BIGINT(20) NOT NULL,
    PRIMARY KEY (`spot_id`, `food_id`),
    INDEX `fk_tour_spot_food_food_id_idx` (`food_id` ASC)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tour_spot_hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tour_spot_hotel`
(
    `id`            BIGINT(20)                                                        NOT NULL AUTO_INCREMENT,
    `name`          VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '标题',
    `description`   TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci'         NULL DEFAULT NULL COMMENT '描述(富文本)',
    `price_average` INT(11)                                                           NULL DEFAULT NULL COMMENT '人均价格',
    `longitude`     DOUBLE(10, 6)                                                     NULL DEFAULT NULL COMMENT '经度',
    `latitude`      DOUBLE(10, 6)                                                     NULL DEFAULT NULL COMMENT '纬度',
    `location_id`   SMALLINT(5)                                                       NULL,
    `location`      VARCHAR(512) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '吃的位置',
    `phone`         VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '电话',
    `like_count`    INT(11)                                                           NULL DEFAULT NULL COMMENT '点赞数量',
    `collect_count` INT(11)                                                           NULL DEFAULT NULL COMMENT '收藏数量',
    `created_at`    BIGINT(20)                                                        NULL DEFAULT NULL,
    `updated_at`    BIGINT(20)                                                        NULL DEFAULT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tour_spot_hotel_rel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tour_spot_hotel_rel`
(
    `spot_id`  BIGINT(20) NOT NULL,
    `hotel_id` BIGINT(20) NOT NULL,
    PRIMARY KEY (`spot_id`, `hotel_id`),
    INDEX `fk_tour_spot_hotel_rel_hotel_id_idx` (`hotel_id` ASC)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tour_spot_photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tour_spot_photo`
(
    `id`          BIGINT(20)                                                        NOT NULL AUTO_INCREMENT,
    `img_url`     VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL COMMENT '图片 url',
    `description` VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '描述',
    `spot_id`     BIGINT(20)                                                        NULL DEFAULT NULL COMMENT '景点 id',
    `from_id`     BIGINT(20)                                                        NULL DEFAULT NULL COMMENT '照片出现的对象(游记, 评论)的 id',
    `photo_from`  TINYINT                                                           NULL COMMENT 'from_id 对应的类型',
    `author_id`   BIGINT(20)                                                        NULL DEFAULT NULL COMMENT '上传者',
    `like_count`  INT                                                               NULL DEFAULT 0,
    `created_at`  BIGINT(20)                                                        NULL DEFAULT NULL,
    `updated_at`  BIGINT(20)                                                        NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_tour_spot_comment_photo_spot_id_idx` (`spot_id` ASC),
    INDEX `fk_tour_spot_photo_author_id_idx` (`author_id` ASC)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tour_spot_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tour_spot_ticket`
(
    `id`         BIGINT(20)                                                        NOT NULL AUTO_INCREMENT,
    `spot_id`    BIGINT(20)                                                        NULL DEFAULT NULL COMMENT '景点 id',
    `name`       VARCHAR(512) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '门票信息',
    `price`      INT(11)                                                           NULL DEFAULT '0' COMMENT '价格',
    `created_at` BIGINT(20)                                                        NULL DEFAULT NULL,
    `updated_at` BIGINT(20)                                                        NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_tour_spot_ticket_spot_id_idx` (`spot_id` ASC)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tour_travel_notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tour_travel_notes`
(
    `id`            BIGINT(20)                                                        NOT NULL AUTO_INCREMENT,
    `title`         VARCHAR(512) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL COMMENT '标题',
    `content`       TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci'         NULL DEFAULT NULL COMMENT '内容(富文本)',
    `author_id`     BIGINT(20)                                                        NULL DEFAULT NULL COMMENT '作者 id',
    `like_count`    INT(11)                                                           NULL DEFAULT '0' COMMENT '点赞数量',
    `collect_count` INT(11)                                                           NULL DEFAULT '0' COMMENT '收藏数量',
    `share_count`   INT(11)                                                           NULL DEFAULT NULL COMMENT '分享数量',
    `start_time`    BIGINT(20)                                                        NULL DEFAULT NULL COMMENT '出发时间',
    `days_used`     INT(11)                                                           NULL DEFAULT NULL COMMENT '用时(天)',
    `cost_average`  INT(11)                                                           NULL DEFAULT NULL COMMENT '人均花费',
    `created_at`    BIGINT(20)                                                        NULL DEFAULT NULL,
    `updated_at`    BIGINT(20)                                                        NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_travel_notes_author_id_idx` (`author_id` ASC)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tour_travel_notes_spot_rel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tour_travel_notes_spot_rel`
(
    `spot_id`         BIGINT(20) NOT NULL,
    `travel_notes_id` BIGINT(20) NOT NULL,
    PRIMARY KEY (`spot_id`, `travel_notes_id`),
    INDEX `fk_travel_notes_spot_notes_id_idx` (`travel_notes_id` ASC)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
